[[main]]
    identifier = 'articles'
    name = 'Articles'
    url = '/articles/'
    weight = 1
[[main]]
    identifier = 'about-me'
    name = 'About Me'
    url = '/about-me/'
    weight = 2

[[social]]
    identifier = 'linkedin'
    title = 'LinkedIn'
    url = 'https://www.linkedin.com/in/kamil-jakub-rusin/'
    weight = 1
[[social]]
    identifier = 'github'
    title = 'GitHub'
    url = 'https://github.com/nathiss'
    weight = 2
[[social]]
    identifier = 'pubkey'
    title = 'Public Key'
    url = '/pub.key.txt'
    weight = 3
[[social]]
    identifier = 'art'
    title = 'Checkout my vector graphics gallery!'
    url = 'https://nathiss.github.io/Polaris/'
    weight = 4
[[social]]
    identifier = 'rss'
    title = 'RSS Feed'
    url = '/index.xml'
    weight = 5
