title = "MadeByMe"
description = "I'm Kamil I work as a software engineer and this is a collection of all things I've been working on in my personal time."
images = ["polaris-1920x1080.png"]

[author]
fullName = 'Kamil Rusin'
firstName = 'Kamil'
lastName = 'Rusin'

[privacy]
# When this value gets changed, then the consent banner will appear to all users.
consentBannerVersion = "2"
