description = "I'm Kamil I work as a software engineer and this is a collection of all things I've been working on in my personal time."

[author]
fullName = 'Kamil Rusin'
firstName = 'Kamil'
lastName = 'Rusin'
